[default]
database_url ="postgresql+asyncpg://postgres:postgres@localhost:5432/rating"
kafka_bootstrap_servers = "localhost:9092"

[production]
DATABASE_URL = "postgresql+asyncpg://user:pass@host:5432/db"
kafka_bootstrap_servers = "localhost:9092"
