"""Create games and players tables

Revision ID: a31fd094ef40
Revises:
Create Date: 2025-04-13 18:50:41.120001

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a31fd094ef40"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("player1_id", sa.Integer(), nullable=False),
        sa.Column("player2_id", sa.Integer(), nullable=False),
        sa.Column("result", sa.Enum("PLAYER1_WIN", "PLAYER2_WIN", "DRAW", name="gameresult"), nullable=False),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "players",
        sa.Column("player_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("player_id"),
        sa.UniqueConstraint("nickname"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    op.drop_table("games")
    # ### end Alembic commands ###
